baseURL = "https://hardesh.github.io/"
languageCode = "en-us"
title = "Harshal Deshpande"
theme = "ezhil"

copyright = "Copyright © Harshal Deshpande"

# Enable syntax highlighting.
pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Your Google analytics code.
googleAnalytics = "UA-123-45"
# Your Disqus sortname.
disqusShortname = "localhost"

# Number of posts to show in recent posts list (Optional). Defaults to 10.
paginate = 10

# Number of characters to show in summary.
summaryLength = 20

[params]
    # Blog subtitle which appears below blog title. Supports markdown.
    subtitle = "Personal blogpost"

    # Content types which are included in home page recent posts list.
    mainSections = ["about"]

    # Content types which are excludes Disqus comments.
    disableDisqusTypes = ["page"]

    # If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
    featherIconsCDN = true

    # Specify favicon (icons/i.png maps to static/icons/i.png). No favicon if not defined.
    favicon = "icons/i.png"

    # Switch to dark mode or auto detect mode from OS (Optional).
    # "dark" will set mode to dark and "auto" will switch to dark mode if OS is in dark mode.
    mode = "auto" # "dark" or "auto"

    # Custom CSS added to default styles. Files added to `static` folder is copied as it is to
    # root by Hugo. For example if you have custom CSS file under `static/css/custom.css` then
    # you can specify custom css path as `css/custom.css`.
    customCSS = "css/custom.css"
    # Custom CSS added to dark mode style.
    customDarkCSS = "css/custom-dark.css"

    # Custom list of Javascript files to load. Just like custom CSS you can place js files under
    # `static/js` folder and specify path here as `js/script-name.js`. You can also specify full url,
    # for example you may want to include external JS library.
    customJS = ["https://code.jquery.com/jquery-3.4.1.js"]

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Experience"
url = "/experience"
weight = 2

[[menu.main]]
name = "Experience"
url = "/experience"
weight = 3

[[menu.main]]
name = "Old Projects"
url = "/projects"
weight = 4

[[menu.main]]
name = "Notes"
url = "/notes"
weight = 5

[[menu.main]]
name = "Bookshelf"
url = "/Bookshelf"
weight = 6

[[menu.main]]
name = "Podcasts"
url = "/podcasts"
weight = 7

[[menu.main]]
name = "Substack"
url = "https://hardesh.substack.com/"
weight = 8

#[[menu.main]]
#name = "CV"
#url = "https://drive.google.com/file/d/1x24BjJaPYE9HILo5xdMbmuG2BdMtjo5i/view?usp=sharing"
#weight = 5

#[[menu.main]]
#name = "About"
#url = "/about"
#weight = 3

#[[menu.main]]
#name = "Tags"
#url = "/tags"
#weight = 4

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/hardesh"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/harshal-deshpande/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/thehardesh"

[[params.social]]
name = "Youtube"
icon = "youtube"
url = "https://www.youtube.com/user/StormyDoru"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://www.instagram.com/thehardesh/"



# Enable tags.
[taxonomies]
   tag = "tags"